### ISSUE TITLE
Хочется страничку с докладами содержащую больше информации по докладам

### ISSUE THREAD

**Issue by MaxShoshin** [AnatolyKulakov/SpbDotNet#10]
- Фотография спикера (это позволяет быстро понять кто читал доклад - удобно тем у кого хорошая память на лица)
- Сразу ссылки на код, видео, слайды
- Подробное описание доклада
- Ссылка на спикера

Например:
![image](https://user-images.githubusercontent.com/1908345/89407386-5e0f9f80-d727-11ea-89b5-d285a7df03b3.png)

**Comment by MaxShoshin** [comment]
+ Наверное хочется видеть рейтинг доклада.

**Comment by unchase** [comment]
@MaxShoshin эта информация представлена в удобном виде в мобильном приложении ([Android](https://play.google.com/store/apps/details?id=com.dotnetru.droid)).

> * Наверное хочется видеть рейтинг доклада.

Надо сначала понять, как определить этот рейтинг.

**Comment by kulakovt** [comment]
Да, не понятно что такое рейтинг доклада (или спикера)?

**Comment by kulakovt** [comment]
Можем например за абсолютный «Рейтинг» считать количество лайков на YouTube (кажется это самая адекватная метрика что у нас есть) и из него вывести относительный рейтинг доклада среди всех докладов.

**Comment by unchase** [comment]
> Можем например за абсолютный «Рейтинг» считать количество лайков на YouTube (кажется это самая адекватная метрика что у нас есть) и из него вывести относительный рейтинг доклада среди всех докладов.

Технически можно ещё учитывать лайки под постами с анонсами/видео/текстом докладов в соц. сетях (Twitter, VK), но это труднее реализовать.

**Comment by kulakovt** [comment]
> Технически можно ещё учитывать лайки под постами с анонсами/видео/текстом докладов в соц. сетях (Twitter, VK), но это труднее реализовать.

Да, сложно уже найти старые анонсы. Да и лайки под ними неохотно ставят. Обычно по анонсу мало что понятно об итоговом докладе.

Лайки под уже выложенными видео в VK — это более показательный момент. Но опять же, не у всех выступлений есть такие посты, наверняка посты 5 летней давности уже не достать, многие подписаны напрямую в YouTube и не лайкают VK и Twitter. Поэтому лайки в YouTube это самые большие и живые лайки что у нас есть.

**Comment by kulakovt** [comment]
> эта информация представлена в удобном виде в мобильном приложении ([Android](https://play.google.com/store/apps/details?id=com.dotnetru.droid)).

Макс хочет видеть эту информацию в браузере.

**Comment by kulakovt** [comment]
GitHub Wiki не способен показать столько информации :)

![image](https://user-images.githubusercontent.com/11032050/89461649-ebc5ac00-d774-11ea-96e0-94a169c597ea.png)

**Comment by kulakovt** [comment]
Сделал для примера только на текущий год. Посмотрите пожалуйста
https://github.com/AnatolyKulakov/SpbDotNet/wiki/DetailedTalks

Надо:

- У wiki хватило сил только на отображение одного года. Надо сделать за все года (может быть нам подойдёт paging — добавить ссылку «_Следующий год_» и генерить по годам?)
- Придумать нужен ли нам Рейтинг Доклада и если нужен, то как его считать?

**Comment by MaxShoshin** [comment]
Круто, а еще хочется наверное что-то подобное вот здесь:
https://github.com/AnatolyKulakov/SpbDotNet/wiki/SpbDotNet


Про рйтинги:
Ну вот тут есть рейтинг:
https://github.com/AnatolyKulakov/SpbDotNet/wiki/LikedVideos

Давайте придумаем формулу, чтобы из четырех чисел получалось одно. 
Например: Like  * Просмотров /  ((Dislike * 5 + 1)  * Max(Просмотров) + Количество дней от публикования до текущей даты).
Я бы не учитывал количество комментариев - их очень уж незначительное количество. И не понятно как их оценивать.

Давайте с какой-нибудь начнем, потом подтюним.

**Comment by kulakovt** [comment]
> Круто, а еще хочется наверное что-то подобное вот здесь

Не получится там, слишком много докладов. Я надеюсь, что хотябы на 1 год хватит. И там список митапов, не докладов. Им конечно тоже нужно придать более красивый вид, но я бы оставил это уже для сайта.

> Ну вот тут есть рейтинг

Это не рейтинг. Это количество лайков. Рейтинг — относительный. Лайки — абсолютны. Можно из лайков сделать рейтинг, разделив на общее количество, например.

Учитывать несколько параметров безусловно ещё лучше чем просто лайки. Но формулу ты так просто не выведешь. Это очень сложная статистика. Нужна уже готовая и откалиброванная. Иначе получится просто провокация с нашей стороны.

**Comment by MaxShoshin** [comment]
Ну не будет тебе готовой и откалиброванной формулы для наших данных.
Давай просто тогда два числа: количество лайков, количество просмотров.

**Comment by kulakovt** [comment]
> Ну не будет тебе готовой и откалиброванной формулы для наших данных

Да полно таких формул, исследований и статей. В нашей ситуации нет ничего уникального. Люди меряются рейтингами уже много веков. Проблема для непосвящённого человека — только отыскать правильную и всё.

> Давай просто тогда два числа: количество лайков, количество просмотров.

Нельзя просто 2 числа. Они абсолютные. Для читателя число «42» ничем не отличается от «420». Это хорошо или плохо? Это просто числа в вакууме, которые без привязки к линейке никакого смысла не имеют. Поэтому надо из них формировать рейтинг.

**Comment by kulakovt** [comment]
Сделал странички по всем годам и добавил секцию «[Детализированные списки докладов](https://github.com/AnatolyKulakov/SpbDotNet/wiki#%D0%94%D0%B5%D1%82%D0%B0%D0%BB%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B8-%D0%B4%D0%BE%D0%BA%D0%BB%D0%B0%D0%B4%D0%BE%D0%B2)» к домашней страннице.

**Comment by MaxShoshin** [comment]
Отсортируй список по годам в обратном порядке

**Comment by MaxShoshin** [comment]
2019 год не открывается - типа слишком долго.... видимо надо бить еще меньше...

**Comment by kulakovt** [comment]
> Отсортируй список по годам в обратном порядке

Готово

> 2019 год не открывается - типа слишком долго.... видимо надо бить еще меньше...

Выбросил первые 20% докладов в этом году. Для пруфа — не критично, на сайте будут все. Замарачиваться сейчас с двойным разбиением года не хочется.

**Comment by kulakovt** [comment]
Задача сделана.

Но без рейтингов. Вопрос рейтинга слишком спорный и сложный. Нужно обсуждать его отдельно, после тщательных исследований существующих подходов и проверенных практик.
