### ISSUE TITLE
Хочется страничку со списком всех докладчиков

### ISSUE THREAD

**Issue by MaxShoshin** [AnatolyKulakov/SpbDotNet#11]
- Фотография докладчика
- Описание докладчика
- Контакты
- Список докладов (если докладов много - можно обрезать)

**Comment by unchase** [comment]
@MaxShoshin эта информация представлена в удобном виде в мобильном приложении ([Android](https://play.google.com/store/apps/details?id=com.dotnetru.droid)).

**Comment by kulakovt** [comment]
@MaxShoshin , а можешь подробнее описать пользовательский сценарий? Зачем это может понадобиться и как ты хочешь эту страничку использовать?

**Comment by MaxShoshin** [comment]
@unchase в приложении я смотрю только тогда, когда я далеко от компа - в мобильнике - там и экран маленький и клавиатура дурацкая.... Так что если есть web версия - то я предпочту ее.

**Comment by MaxShoshin** [comment]
@AnatolyKulakov ,
Мне иногда интересно посмотреть кто вообще делал доклады.
Иногда я с интересом обнаруживаю знакомые мне физиономии. 

Просто когда одна страница под докладчика - это хорошо тогда, когда ты знаешь кого искать. А если ты помнишь только лицо - то список с фотомордами - незаменим. Но просто фотоморды выдать - так тоже не удобно, когда есть список докладов рядом - ты сразу можешь оценить тот это человек или нет без лишних кликов.

В общем, почти полноценная социальная сеть... :)

**Comment by kulakovt** [comment]
Разве это не тоже самое что и #10 ?

**Comment by MaxShoshin** [comment]
Нет, тут только докладчики и название докладов... Тут заточено под поиск человека, там под поиск доклада...

**Comment by kulakovt** [comment]
Кажется что это очень редкая или даже уникальная ситуация. Которая в большинстве случаев покрывается списком докладов или просто лицами докладчиков (как в мобилке). Выгружать просто дамп всей базы на одну страничку кажется не самым удачным UX решением.

**Comment by kulakovt** [comment]
Слишком редкий сценарий использования
