### ISSUE TITLE
Кнопки для скачивания мобильного приложения

### ISSUE THREAD

**Issue by kulakovt** [AnatolyKulakov/SpbDotNet#7]
Официальные кнопки для скачивания приложения из магазинов выглядят слишком неконсистентно, если из расположить рядом.

![Google play button](https://i.imgur.com/YQzmZi9.png)
![Apple store button](https://i.imgur.com/GdGqPMY.png)

Мы не можем себе позволить подобное уродство.

Необходимо, оставив содержимое, перерисовать кнопки в едином стиле. А именно, у результатов должны быть:

- одинаковый размер (тот который побольше)
- одинаковая форма
- одинаковая область под текст и логотип
- одинаковый размер логотипа

**Comment by kulakovt** [comment]
Мобильное приложение заброшено и не развивается

**Comment by unchase** [comment]
Не хватает времени на него, возможно, ещё вернусь к доработке.
Вопрос: как часто им вообще пользуются? Есть ли смысл тратить время?

**Comment by kulakovt** [comment]
К сожалению вся статистика у @pfedotovsky . У меня нет сведений об использовании.
Но уже больше года висит баг о том что [приложение не обновляет контент](https://github.com/DotNetRu/App/issues/258). А по факту эта проблема начала проявляться ещё раньше. Т.е. основная функциональность не работает.

**Comment by unchase** [comment]
А мы можем повторно попросить @pfedotovsky обратить внимание на этот баг?

Какие значения *realmServerUrl* и *realmName* сейчас актуальны для `$"realms://{realmServerUrl}/{realmName}"`?

**Comment by kulakovt** [comment]
Попробовать конечно всегда можно.
Все настройки реалма есть только у Паши. Я ничего не знаю.

**Comment by unchase** [comment]
Я попробовал обновить через API (`DotNetRu.AzureService`) online Realm, который есть в конфигурации к тестовому проекту `DotNetRu.RealmTests`:
dotnetru.de1a.cloud.realm.io
dotnetru_050919

Вроде всё корректно отработало, дошло до конца (как минимум, во временном файле Realm'а оказались записи о SpbDotnet-68). 

![image](https://user-images.githubusercontent.com/29679226/115306247-399e0b00-a170-11eb-8935-37841fe6d05f.png)

И в debugger'е другие новые встречи были точно. Значит, сам процесс обновления работоспособен, насколько я могу судить.
Но я подозреваю, что это не боевой (или не актуальный для приложения) адрес.

@pfedotovsky можешь подтвердить, что для dotnetru_050919 данные обновились?
@kulakovt а git-хук, который дёргает обновление, что-нибудь логирует при этом?

**Comment by unchase** [comment]
Offline-выгрузка (обновление) точно работает:

![image](https://user-images.githubusercontent.com/29679226/115307516-fe9cd700-a171-11eb-9919-87b592e42d1d.png)

![image](https://user-images.githubusercontent.com/29679226/115307619-25f3a400-a172-11eb-8fb0-6642e88f02bf.png)

**Comment by kulakovt** [comment]
Да, для хука есть логи. У него всё зелёное.

![image](https://user-images.githubusercontent.com/11032050/115308739-dca45400-a173-11eb-9790-c3b30bee326a.png)

**Comment by unchase** [comment]
Сдаётся мне, что приложение просто не на тот Realm смотрит. А по факту обновление проходит успешно.

**Comment by unchase** [comment]
При локальной отладке `DotNetRu.Android` при запуске обнаружил `NullReferenceException` в [этом месте](https://github.com/DotNetRu/App/blob/1937fbe6997ff97ff3438754f5975f029217e99b/DotNetRu.DataStore.Audit/Services/RealmService.cs#L125) в `RealmService.cs`:

![image](https://user-images.githubusercontent.com/29679226/115310787-1e82c980-a177-11eb-8e6b-d37a8dd682ec.png)

![image](https://user-images.githubusercontent.com/29679226/115310863-440fd300-a177-11eb-9ecd-e2bdc88fa45b.png)

```
  at Realms.Utils.RealmSyncManager+<>c__DisplayClass3_1.<MoveRealmObjects>b__1 (Realms.RealmObject newObject) [0x0000c] in <f6a42563b55f4a3e892a50c8d6ac0e28>:0 
  at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0002c] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Linq/src/System/Linq/AnyAll.cs:38 
  at Realms.Utils.RealmSyncManager+<>c__DisplayClass3_0.<MoveRealmObjects>b__0 (Realms.RealmObject obj) [0x00031] in <f6a42563b55f4a3e892a50c8d6ac0e28>:0 
  at System.Linq.Enumerable+WhereListIterator`1[TSource].MoveNext () [0x00037] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.Linq/src/System/Linq/Where.cs:351 
  at Realms.Utils.RealmSyncManager.MoveRealmObjects (Realms.Realm fromRealm, Realms.Realm toRealm, System.String className, System.String primaryKeyPropertyName) [0x0007d] in <f6a42563b55f4a3e892a50c8d6ac0e28>:0 
  at Realms.Utils.RealmSyncManager.UpdateRealm (Realms.Realm fromRealm, Realms.Realm toRealm) [0x00090] in <f6a42563b55f4a3e892a50c8d6ac0e28>:0 
  at DotNetRu.DataStore.Audit.Services.RealmService.GetCloudRealm (System.Uri realmServerUri, System.Uri realmDatabaseUri) [0x001c4] in e:\Work\Git\GITHUB\FORKS\App\Temp258\App\DotNetRu.DataStore.Audit\Services\RealmService.cs:125 
```

Возможно из-за этого обновление и не проходит. Если в приложении поведение схожее, то обновление валится в этом месте, тогда приложением используется последняя версия offline Realm, которая есть в текущей версии приложения.

Это предположение, над изучить.

**Comment by kulakovt** [comment]
У Паши были централизованные логи, если я не ошибаюсь. Наверное по ним он может легко подтвердить эту версию.

**Comment by unchase** [comment]
Не могу найти `Realms.Utils.pdb` файл, чтобы продебажить внешнюю библиотеку, в которой возникает исключение. Даже в nuget-пакете нет pdb-файлов(

![image](https://user-images.githubusercontent.com/29679226/115312145-7b7f7f00-a179-11eb-9c1a-889a95b3b6ce.png)

Но проблема возникает где-то здесь:

![image](https://user-images.githubusercontent.com/29679226/115311984-38251080-a179-11eb-9d6b-7d0df3f6a3f8.png)

Может есть какой-нибудь другой способ дебага dll?

**Comment by kulakovt** [comment]
@unchase dotPeek умеет притворяться символьным сервером и генерить pdb на лету к любой запрашиваемой dll.
dnSpy тоже умеет отлаживать декомпелированный код.

**Comment by unchase** [comment]
@kulakovt завёл PR https://github.com/pfedotovsky/realm-dotnet-utils/pull/1 с исправлением.
Теперь дело за @pfedotovsky, когда найдёт время слить. Далее проверю в приложении.
