### ISSUE TITLE
Правки для профиля Андрея Тарицына

### ISSUE THREAD

**Issue by Taritsyn** [AnatolyKulakov/SpbDotNet#8]
Здравствуйте, Анатолий!

В мой профиль нужно внести следующие правки:

 1. Убрать упоминание о том, что я работаю в Quantum Art, потому что я там не работаю уже 7 лет. В данный момент, я не представляю какую-либо организацию. Если нужно что-то указать, то можете написать «Собственные некоммерческие проекты».
 1. Заменить неработающую ссылку на мой блог (`https://taritsyn.ru/` -> `http://www.taritsyn.ru/`).
 1. Поскольку в английском языке нет слова «minificator», то файл `WebMarkupMin-HTML-minificator-for-the-platform-NET.md` нужно переименовать в `WebMarkupMin-HTML-minifier-for-the-NET-platform.md`.
 1. В описании доклада нужно заменить текст «Будут измерены эффективность» на «Будет измерена эффективность». 

Все эти изменения я оформил в виде пулл реквеста, который находится во внешнем репозитории - https://github.com/Taritsyn/SpbDotNet-wiki.

Чтобы присоединить этот пулл реквест нужно выполнить на локальной копии репозитория `SpbDotNet.wiki` следующие команды:

```
git remote add Taritsyn git://github.com/Taritsyn/SpbDotNet-wiki.git
git pull Taritsyn master
git push
```

**Comment by kulakovt** [comment]
Здравствуйте @Taritsyn 

Большое спасибо за исправления. Но Эта wiki является лишь результатом кодогенерации источником которой служит проект [DotNetRu/Audit](https://github.com/DotNetRu/Audit). Мы внесём все предложенные вами изменения туда. Или вы сами может предложить Pull Request со всеми исправлениями в репозиторий-источник.

/cc @Justice01

**Comment by Taritsyn** [comment]
Элементы `CompanyName` и `CompanyUrl` могут содержать пустые значения?

**Comment by kulakovt** [comment]
Пустые нет. Но они могут отсутствовать. И это ваш случай

**Comment by Taritsyn** [comment]
```xml
        <xs:element name="CompanyName" type="requaredString" minOccurs="0" maxOccurs="1" />
        <xs:element name="CompanyUrl" type="requaredUri" minOccurs="0" maxOccurs="1" />
```

Да, это видно из схемы.

**Comment by Taritsyn** [comment]
Хорошо. Я подготовлю пулл реквест.

И еще вопрос. Что обычно содержится в элементе `ContactsUrl`?

**Comment by Taritsyn** [comment]
Отправил [пулл реквест](https://github.com/DotNetRu/Audit/pull/72) в репозиторий Audit. Спасибо за информацию!

**Comment by kulakovt** [comment]
> И еще вопрос. Что обычно содержится в элементе `ContactsUrl`?

Ссылку на контакты, которая не попадает под другие Url'ы. Например LinkedIn.

**Comment by Taritsyn** [comment]
Да, у большинства указана ссылка на LinkedIn, но у докладчиков, которые имеют блоги, указана ссылка на раздел «Обо мне». Поэтому я решил указать следующий адрес - https://taritsyn.wordpress.com/about-me/.

Немного отойду от темы. Как я понял, данная информация собирается не только для мобильного приложения, но для сайта [DotNet.Ru](https://dotnet.ru/), т.е. в какой-то момент на сайте появится раздел «Докладчики» (наподобие [этого](https://www.moscowjs.ru/speakers))?

**Comment by kulakovt** [comment]
Да «about-me» это правильная ссылка для ContactsUrl.

Да, вы правы. Сейчас Аудит активно используется нашим [мобильным приложением](https://github.com/DotNetRu/App) и в [моей wiki](https://github.com/AnatolyKulakov/SpbDotNet/wiki). Которая является прототипом того, что я хочу сделать на сайте DotNet.Ru . Основная часть этого процесса уже завершена, остались задачи связанные с инфраструктурой. Надеюсь что в ближайшем времени я перенесу раздел со всеми материалами на сайт.

**Comment by Taritsyn** [comment]
Это очень полезный функционал. Он «оживит» сайт DotNet.Ru, люди будут чаще на него заходить.

Инфраструктура будет по-прежнему использовать Wyam?

**Comment by kulakovt** [comment]
Скорее всего, да. При всех его недостатках, лучшей альтернативы я не нашёл.
